image: python:latest

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pylint -d C0301 project/*.py

pytest:
  stage: Test
  script:
  - cd project/test/;pytest -v
